# Generated by Django 4.0.4 on 2022-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zip_code',
            field=models.CharField(max_length=8),
        ),
    ]
