# Generated by Django 4.0.4 on 2022-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_teacher_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
