# Generated by Django 4.0.4 on 2022-05-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_teacher_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cod_ibge',
        ),
    ]
